### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by mahirabidi12** [AdityaSinha2305/ForkTheCaptcha#17]
I would love to create a footer for your website . Please assign me the issue under hacktoberfest tag

**Comment by AdityaSinha2305** [comment]
Assigned, you can now start working on this issue.

**Comment by mahirabidi12** [comment]
I ahve send you a pull request . I have made the required changes and would be making more under different issues.
<img width="1439" alt="Screenshot 2024-10-13 at 12 45 17 AM" src="https://github.com/user-attachments/assets/50d11a66-50c0-4a5e-aa2b-fc1bcf4c503c">
Please merge it and don't forget to use hacktoberfest label.

**Comment by AdityaSinha2305** [comment]
@mahirabidi12 Your update is great!!
Could you shift navbar at top?
If you are still working on this issue do confirm it.

**Comment by mahirabidi12** [comment]
yes I have shifted the nav bar at the top and also send you the pull request.

**Comment by mahirabidi12** [comment]
Please accept the pull request and merge it under the hacktoberfest label

**Comment by AdityaSinha2305** [comment]
@mahirabidi12 Are you still working for footer issue?

**Comment by mahirabidi12** [comment]
Yes , i am working on the footer issue and i have also submitted a pull request to merge my nav bar .
