### ISSUE TITLE
Alignment adjustment

### ISSUE THREAD

**Issue by Pudi-Sravan** [AdityaSinha2305/ForkTheCaptcha#2]
Fixed the alignment of the container and changed the cursor style for the start.
**Screenshot:**
![Screenshot from 2024-10-12 15-25-25](https://github.com/user-attachments/assets/11b9ff3a-40ce-406b-b660-99c515cc8e5d)
Could you assign this for me

**Comment by AdityaSinha2305** [comment]
Assigned
