### ISSUE TITLE
To reset the input box

### ISSUE THREAD

**Issue by kshitijakarsh** [AdityaSinha2305/ForkTheCaptcha#20]
The captcha text inside the input box doesn't change if the captcha is reset.
To Fix : Resetting the input box every time the captcha gets changed.

<img width="1440" alt="Screenshot 2024-10-13 at 1 33 00 AM" src="https://github.com/user-attachments/assets/4fc04354-6372-4f5b-b28e-93dfb0f48dea">
<img width="1440" alt="Screenshot 2024-10-13 at 1 33 08 AM" src="https://github.com/user-attachments/assets/47467c66-5da3-4c30-be44-78c2ae05d73b">

**Comment by saarimshaikh** [comment]
This issue looks interesting to solve. Please assign me this issue under the hacktoberfest 2024 tag

**Comment by saarimshaikh** [comment]
I made the necessary changes to reset the input box when the captcha is reset. Please do check.

**Comment by saarimshaikh** [comment]
@AdityaSinha2305 Thanks for assigning this task to me, can you also add Hacktoberfest 2024 tag to this issue?
