### ISSUE TITLE
Fixing the UI of the homepage

### ISSUE THREAD

**Issue by divyansharma001** [AdityaSinha2305/ForkTheCaptcha#22]
![image](https://github.com/user-attachments/assets/9afbd631-e823-4ecb-83aa-1359d02b654f)
This box looks bad. There is need of improvement in UI.
Please assign this to me I'll fix it. If possible add hackoctoberfest tags to it.

**Comment by AdityaSinha2305** [comment]
Assigned, you can start working now on this issue.
Do read the guidelines before contributing.
Thanks!

**Comment by divyansharma001** [comment]
can you please add hackoctober fest tag to this?

**Comment by AdityaSinha2305** [comment]
@divyansharma001 Are you working on this issue?

**Comment by divyansharma001** [comment]
Yes

**Comment by AdityaSinha2305** [comment]
Okay, don't forget to sync your fork regularly.

**Comment by walkoverr** [comment]
@AdityaSinha2305 If not done could you please assign this task to me

**Comment by AdityaSinha2305** [comment]
Hey @walkoverr I have assigned this issue, you can start working now.

**Comment by divyansharma001** [comment]
I've already done PR to this https://github.com/AdityaSinha2305/ForkTheCaptcha/pull/61
Please review
