### ISSUE TITLE
Feat: Add responsiveness to the captcha card

### ISSUE THREAD

**Issue by munna-yadav** [AdityaSinha2305/ForkTheCaptcha#23]
The captcha string becomes small while the reset and the volume buttons are of same size making it difficult to read.
![image](https://github.com/user-attachments/assets/c4f15deb-2a73-4c93-990f-ebca4ab835ac)

**Comment by AdityaSinha2305** [comment]
Assigned, you can start working now!
Don't forget to read the guidelines before contributing.
