### ISSUE TITLE
Fixing the logic

### ISSUE THREAD

**Issue by kshitijakarsh** [AdityaSinha2305/ForkTheCaptcha#26]
Fixing the logic of the code to avoid getting "undefined" in the captcha and making the program more efficient when regenerating the captcha.

Assign it to me.

<img width="1440" alt="Screenshot 2024-10-13 at 12 28 22 PM" src="https://github.com/user-attachments/assets/3695b816-4c88-45fb-b04f-6af5bb91d40e">

**Comment by AdityaSinha2305** [comment]
Assigned, you can start working now.
Before contributing read the guidelines.
Make sure your repo is up-to-date with main branch.
Thanks!!

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh Are you working on this issue?

**Comment by kshitijakarsh** [comment]
I'm, I'll raise another PR to solve this
