### ISSUE TITLE
fix: Refresh the captcha and reset the input area

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#27]
If the entered captcha is **invalid** refresh the captcha and reset the input area.

**Comment by kshitijakarsh** [comment]
hey @AdityaSinha2305, I think this issue is similar to what I raised, please check it

**Comment by AdityaSinha2305** [comment]
@kshitijakarsh In that issue after clicking refresh icon the captcha is refreshed and the input area is reset.
But in this issue if captcha is invalid after clicking the submit then the captcha should refreshed and the input area.

**Comment by Pudi-Sravan** [comment]
@AdityaSinha2305 could you assign this for me

**Comment by Pudi-Sravan** [comment]
@AdityaSinha2305 may i make the changes after the changes for the keydown equal to enter case(which is currently not merged) or may i do the changes basing the current main branch

**Comment by AdityaSinha2305** [comment]
@Pudi-Sravan Make changes in a separate branch (base as main) for new features.
Sync your fork with main.
