### ISSUE TITLE
Fix background image

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#3]
Apply background image only where captcha and icons are displaying and that too before the input area.
Captcha content and icons should display over the image.
Size of Background-image of captcha should vary depending on the captcha content.

**Comment by Pudi-Sravan** [comment]
so here do we need to add a different background image for the captcha or the same one we used as background

**Comment by syamjir** [comment]
assign me to this task

**Comment by Pudi-Sravan** [comment]
did you mean it in this way,if yes please assign this to me.
**Screenshot:**
![Screenshot from 2024-10-12 15-57-44](https://github.com/user-attachments/assets/99e81336-ecc7-4333-b8f2-32bfb283ad7c)

**Comment by AdityaSinha2305** [comment]
@Pudi-Sravan The change is correct but you have exchanged both the image.

**Comment by AdityaSinha2305** [comment]
@syamjir  @Pudi-Sravan is currently working on this issue.

**Comment by syamjir** [comment]
@AdityaSinha2305 ok thank u .

**Comment by Pudi-Sravan** [comment]
@AdityaSinha2305 could you please once go through the changes and merge if everything looks good.
i have first sent a pr for the alignment and next for this background.

**Comment by Pudi-Sravan** [comment]
@AdityaSinha2305 i think this issue has been already resolved and merged so i think this can be closed
