### ISSUE TITLE
Start Button Alignment

### ISSUE THREAD

**Issue by Adi-204** [AdityaSinha2305/ForkTheCaptcha#5]
Fixed alignment of "START" button is centered irrespective of the CAPTCHA length.

Screenshot: 

![Screenshot 2024-10-12 160632](https://github.com/user-attachments/assets/7c74b7ef-b01b-468b-a2cb-cb184c367e70)

Could you assign this for me

**Comment by AdityaSinha2305** [comment]
@Adi-204  Assigned, you can now work on this issue.

**Comment by AdityaSinha2305** [comment]
This issue is solved already by other peers.
You can now work on other issues.
Thank you!
