### ISSUE TITLE
feat: Math captcha

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#69]
Implement an option for math captcha and generate math captcha accordingly.
Example:  
1. Captcha :  4 + 8 , Valid : 12
2. Captcha :  9 - 3 , Valid : 6
and many more.

NOTE : Implement an option to choose between text and math captcha.
Text captcha is already been there.

**Comment by Srijatalamarla** [comment]
Hello!
I would like to work on it.
