### ISSUE TITLE
feat: UI of login page 

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#90]
After submitting the valid captcha there is a login page. Create an unique UI for the login page.

![image](https://github.com/user-attachments/assets/324746ce-794d-4cc8-8935-b0852cd4a719)

**Comment by VSwaroop07** [comment]
Assign it to me.

**Comment by AdityaSinha2305** [comment]
@VSwaroop07 Assigned, you can starting working on this issue.
Note: Read contribution guidelines before contributing.

**Comment by VSwaroop07** [comment]
![image](https://github.com/user-attachments/assets/5d0b2a7a-769e-4cb3-8b84-38338d347ab3)
Is this good suggest of any changes needed
