### ISSUE TITLE
feat: Add signup feature in login page

### ISSUE THREAD

**Issue by AdityaSinha2305** [AdityaSinha2305/ForkTheCaptcha#96]
Add signup feature in login page and redirect it to signup page.

![image](https://github.com/user-attachments/assets/ebdc560c-820b-4f35-b001-ea000561aa75)

**Comment by InderParmar** [comment]
Hi Aditya, This project looks really interesting to me, can you assign this issue to me, will start working on it asap?

**Comment by InderParmar** [comment]
Hi @AdityaSinha2305 , the issue is resolved, i have linked the pull request, can you please review and merge the pull request, please let me know if there are any concerns. Thank you!
